spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: d202402706
    password: "1234"
    data-source-properties:
      implicitStatementCacheSize: 0

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      jdbc:
        use_scrollable_resultset: false
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: TRACE
